config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  root to: 'toppages#index'
  get 'toppages/index'
  resources :users
  resources :posts do
    collection {post :import}
  end
  get 'download_csv', to: "posts#download_csv"
  get 'search' => 'posts#search'
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :question, presence: true
  validates :answer, presence: true
  validates :question_type, presence: true

  def self.search(keyword)
    where(["cast(id as text) like? OR question_type like? OR title like? OR question like? OR answer like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      task = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      task.attributes = row.to_hash.slice(*updatable_attributes)
      task.save
    end
  end

# 更新を許可するカラムを定義
  def self.updatable_attributes
    ["title", "question_type", "question", "answer", "questioner"]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: %i[update]
before_action :current_session_user, {only: [:create, :index, :search, :update, :destroy, :import]}
skip_before_action :verify_authenticity_token

  def create
    @post = Post.new(post_params)
    if @post.save
        @post.update(email: current_user.email.sub!(/@.*/m, ""))
    end
    redirect_to posts_path
    @posts = Post.all
  end

  def index
      @posts = Post.all.order(created_at: :desc)
      @post = Post.new
      respond_to do |format|
        format.html
        format.csv do
          products_csv
        end
      end
  end
  def search
    @posts = Post.search(params[:keyword]).where(question_type: params[:question_type]).order(created_at: :desc)
    @keyword = params[:keyword]
    @question_type = params[:question_type]
    @scroll ="scroll"
    render "index"
  end

  def update
    if @post.update!(post_update_params)
      render json: @post
    else
      head :bad_request # ①ステータスコードを400番で返す
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post_id = @post.id
    @msg = "削除が成功"
    @post.destroy
  end

  def post_update_params
  params.require(:post)
        .permit(:answer, :question)
  end

  def import
    if params[:file] != nil
      Post.import(params[:file])
      redirect_to posts_path
      flash[:success] = 'csvインポート成功'
    else
      flash[:alert] = 'csvをインポートできませんでした'
      redirect_to posts_path
    end
  end

  def download_csv
  send_file(
    "#{Rails.root}/public/faq_template.csv",
    filename: "faq_template.csv",
    type: "application/csv"
  )
  end

  private

  def products_csv
    bom = "\uFEFF"
    csv_date = CSV.generate(bom) do |csv|
    csv_column_names = ["ID","Type", "Title", "Question","Answer","Questioner"]
    csv << csv_column_names
    @posts.each do |post|
      csv_column_values = [
        post.question_id,
        post.question_type,
        post.title,
        post.question,
        post.answer,
        post.questioner
      ]
      csv << csv_column_values
      end
    end
      send_data(csv_date,filename: "faq.csv")
    end
    def set_post
      @post = Post.find(params[:id])
    end
    def post_params
      params.permit(:title, :question, :answer, :question_id, :question_type, :email, :questioner)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/destroy.js.erb
$('#post-<%= @post_id %>').html('');
$('#alert-message').html('<div class="alert alert-success"><%= @msg %></div>')

app/views/posts/index.html.slim
.notifications
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)
.col-10.offset-1
 .span-right.col-12
  = current_user.email
  br
  = link_to "ログアウト", destroy_user_session_path, method: :delete
 = form_with url: posts_path, method: :post, local: true do |form|
  p
    span 事業
    br
    = form.collection_select :question_type, Post.select(:question_type).distinct, :question_type, :question_type,{}, {class: 'program-type-form'}
    = form.text_field :question_type, :class => "program-type-text"
    i.fa.fa-plus.fa-plus-form aria-hidden="true"
    br
    = form.label :title, "件名"
    br
    = form.text_field :title, placeholder: "任意"
    br
    = form.label :title, "質問者"
    br
    = form.text_field :questioner, placeholder: "任意"
  p
    = form.label :question, "Question", class: "question-label"
    br
    = form.text_area :question, class: "enter-boxes col-11"
  p
    = form.label :answer, class: "answer-label"
    br
    = form.text_area :answer, class: "enter-boxes col-11"
  = form.submit "追加", class: "offset-10"

 .search-form
  = form_with url: search_path, method: :get, local: true do |f|
    = f.collection_select :question_type, Post.select(:question_type).distinct, :question_type, :question_type, selected: @question_type
    = f.text_field :keyword, value: @keyword, class: "col-sm-3 col-md-5 col-lg-6 search-box"
    = f.submit "検索"
    = link_to posts_path(format: :csv), class: "csv-download btn btn-sm btn-success" do
      span csv出力
      i.fa.fa-download aria-hidden="true"
    span.btn.btn-sm.btn-success.csv-download.import-button csvインポート
  = form_tag import_posts_path, multipart: true do
    .file-import-box
     = link_to download_csv_path, class: "btn btn-sm btn-dark", data: { confirm: 'csvインポート用のテンプレートをダウンロードしますか？' } do
      span テンプレート
      i.fa.fa-download aria-hidden="true"
     = file_field_tag :file
     = submit_tag "インポート", class: "import-submit"
 .post-list
  - @posts = @posts.page(params[:page]).per(5)
  - @posts.each do |post|
    br
    div id="post-#{post.id}"
      .qa-container
       .type-and-id
        span.q-type
         = post.question_type
        span.q-id
         - if Post.where(question_type: post.question_type, id: [..post.id]) != nil
          = Post.where(question_type: post.question_type, id: [..post.id]).count
        -if post.title?
         span：
         span
          = post.title
       = link_to post_path(post), method: :delete, remote: true, data: { confirm: '削除しますか？' } do
          i.fa.fa-trash aria-hidden="true"
       |<span data-comment-id=#{ post.id } class="js-edit-comment-button">
          <i class="fas fa-edit text-primary"></i>
        </span>
       |
        <div id="js-question-#{ post.id }">
         <span style="display: none;" class="target-#{ post.id }" id="js-Q-question-#{ post.id }">
          Q.
        　</span>
         <textarea style="display: none;" id="js-textarea-question-#{ post.id }" class="form-control comment-post-error">
          #{ post.question }
         </textarea>
        </div>
        <div id="js-comment-#{ post.id }">
         <span style="display: none;" id="js-A-comment-#{ post.id }">
          A.
        　</span>
         <textarea style="display: none;" id="js-textarea-comment-#{ post.id }" class="form-control comment-post-error">
         #{ post.answer }
         </textarea>
         <div id="js-comment-button-#{ post.id }" style="display: none;">
         <br>
            <button data-cancel-id=#{ post.id } type="button" class="btn btn-light comment-cancel-button offset-6 offset-md-8">キャンセル</button>
            <button data-update-id=#{ post.id } type="submit" class="btn btn-success comment-update-button">更新</button>
          </div>
         </div>
      div id="hello-#{ post.id }"

       span.date 追加日時：
       span.date
        =post.created_at.strftime("%Y年%-m月%-d日 %-H時%-M分")
         br
         =post.email
       -if post.questioner?
        br
        span.questioner 質問者：
        span.questioner
         =post.questioner
       br
       .q-box
        |<span class="q-letter">  Q.
         </span>
         <p id="js-question-label-#{ post.id }" class="questionlabel">
         #{safe_join(post.question.to_s.split("\n"),tag(:br))}
         </p>
       br
       .a-box
        |<span class="a-letter"> A.
         </span>
         <p id="js-comment-label-#{ post.id }" class="answerlabel">

         #{safe_join(post.answer.to_s.split("\n"),tag(:br))}

         </p>
 = paginate @posts
p.scroll
  = @scroll
|<script>
  if (!$('.scroll').is(':empty')){
  const search = $('.search-form').offset();
  window.scrollTo({top: 600, behavior: 'instant'});
  }
 </script>